Adding POX Docker Image
KatharaFramework/Docker-Images pull request #13
Opened 2024-02-13 17:55 UTC by RicGobs

Hi,

Here it is a **Docker POX image**, to allow using POX without importing POX as a Git submodule. The new image is based on the kathara/base image.

The Docker image is needed for the sdn-openflow labs (located in the main labs directory).

2024-02-20 11:06 UTC, tcaiazzi approved these changes

2024-02-27 10:26 UTC, Skazza94 requested changes
Hi @RicGobs,
thanks for the PR. I have some changes to ask.

Thank you!
Mariano.

2024-02-27 10:26 UTC, Skazza94 commented on pox/Dockerfile
> +RUN apt install -y zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libsqlite3-dev libreadline-dev libffi-dev curl libbz2-dev
After compiling Python3.9, I think you can remove these libraries.

2024-02-27 10:26 UTC, Skazza94 commented on pox/Dockerfile
> +    chmod +x /pox/pox.py
Please add the following snippet at the end of the Dockerfile to clean up caches/other:
```
RUN apt clean && \
    rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/*
```

2024-02-28 20:43 UTC, RicGobs commented
Hi @Skazza94,

I have done the following:
- added the snippet code at the end (for the cache)
- removed zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libsqlite3-dev libreadline-dev libffi-dev curl libbz2-dev (after their use)
- done a test (it works on my labs)

Tell me if other is needed. Bye
Riccardo

2024-02-29 15:15 UTC, Skazza94 approved these changes
Hi @RicGobs,
thanks for the changes. The PR looks good! 😄

2024-02-29 15:16 UTC, merged