Rebuild images with Debian 12 + Add new suites
KatharaFramework/Docker-Images pull request #9
Opened 2023-08-28 15:20 UTC by Skazza94

**Description**:
This PR updates the Kathará official Docker images. The primary focus of this update is to rebuild the images using Debian 12, a new and up-to-date base, and to introduce additional suites. The key contributions in this PR are outlined below:

1. **Upgrade to Debian 12:**
- The Docker images have been rebuilt using Debian 12 as the base distribution. This transition ensures that the Kathará framework utilizes the latest system improvements, security enhancements, and software packages provided by Debian 12.

2. **Introduction of New Suites:**
   Alongside the Debian 12 upgrade, this PR brings in a set of new suites that offer diverse environments for users to work with. These suites extend the capabilities of the framework, catering to a wider range of use cases and preferences. The complete list includes:
- `kathara/base`: used to build all other images. It contains a variety of network tools and some complex services like bind, apache, etc.
- `kathara/quagga`: extends the base image adding [Quagga](https://www.nongnu.org/quagga/).
- `kathara/frr`: extends the base image adding [FRRouting](https://frrouting.org/).
- `kathara/openbgpd`: extend the base image adding the [OpenBGPD daemon](https://www.openbgpd.org/).
- `kathara/krill`: extends the base image adding [Krill RPKI Certificate Authority](https://www.nlnetlabs.nl/projects/rpki/krill/).
- `kathara/routinator`: extends the base image adding [Routinator RPKI Relying Party](https://www.nlnetlabs.nl/projects/rpki/routinator/).
- `kathara/rpki-client`: extends the base image adding [OpenBGPD RPKI Client](https://www.rpki-client.org).
- `kathara/bird`: extends the base image adding [BIRD](https://bird.network.cz/).
- `kathara/rift-python`: extends the base image adding [Routing In Fat Trees (RIFT) Python Implementation](https://github.com/brunorijsman/rift-python).
- `kathara/sdn`: extends the base image adding [OpenVSwitch](https://www.openvswitch.org/) and [Ryu SDN controller](https://osrg.github.io/ryu/).
- `kathara/p4`: extends the base image adding [Behavioral Model (bmv2)](https://github.com/p4lang/behavioral-model) to compile and run P4-compliant programmable switches.

2023-08-28 15:50 UTC, tcaiazzi approved these changes

2023-09-12 15:48 UTC, lorenzo93 requested changes
Everything ok except one single comment. :)

2023-09-12 15:48 UTC, lorenzo93 commented on base/Dockerfile
Missing `mtr` package according to [this](https://github.com/KatharaFramework/Kathara/issues/238) issue in Kathará

2023-09-12 15:50 UTC, Skazza94 commented on base/Dockerfile
Hi @lorenzo93, added!

2023-09-12 21:50 UTC, lorenzo93 commented on base/Dockerfile
Dear @Skazza94 ,

`mrt` stands for "Multi-Threaded Routing Toolkit" and has nothing to do with `mtr`that stands for "My-Traceroute". I think you mispelled the package name, in fact, the `mrt` package does not even exists in the debian repositories. :)

2023-09-13 16:12 UTC, lorenzo93 approved these changes

2023-09-26 15:07 UTC, merged